### ISSUE TITLE
Display alarm flags in info/update

### ISSUE THREAD

**Issue by gfrn** [JeffersonLab/epics2web#7]
Is there any intention of supporting alarm flags in the near future? Currently, I am facing a situation where it would be most useful to be able to detect and display "invalid" PVs, as that is relevant to a system to a system that depends on said PV. 

Thanks in advance

**Comment by slominskir** [comment]
epics2web only supports the six basic data types, and does not support the compound types (DBR_STS, DBR_TIME, DBR_GR,  and DBR_CTRL).   However, the basic types are generally all you need as you can monitor any field individually (and as many fields as you'd like).  For example monitor the .SEVR field directly to observe alarm state such as INVALID.    

That said, it is possible for an IOC to generate a compound type that contains fields that do not map to the set of individual fields that normally make up the compound type (example: https://github.com/JeffersonLab/wedm/issues/20).  This is arguably a misuse of the CA "contract" in these custom cases.

**Comment by gfrn** [comment]
Thanks for the quick reply,  I was not aware of the possibility to directly monitor individual fields, that does indeed solve my issue. I'll be closing the issue for now
